// <auto-generated />
using System;
using DataBaseInfrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataBaseInfrastructure.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250705180642_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.16");

            modelBuilder.Entity("DataBaseInfrastructure.Models.OurGuild", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("ModeratorRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("QuoteChanelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("DataBaseInfrastructure.Models.OurMember", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OurMembers");
                });

            modelBuilder.Entity("DataBaseInfrastructure.Models.Quote", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnon")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("MsgId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("OurGuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("OurMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OurGuildId");

                    b.HasIndex("OurMemberId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("DataBaseInfrastructure.Models.Quote", b =>
                {
                    b.HasOne("DataBaseInfrastructure.Models.OurGuild", "OurGuild")
                        .WithMany()
                        .HasForeignKey("OurGuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataBaseInfrastructure.Models.OurMember", "OurMember")
                        .WithMany("Quotes")
                        .HasForeignKey("OurMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OurGuild");

                    b.Navigation("OurMember");
                });

            modelBuilder.Entity("DataBaseInfrastructure.Models.OurMember", b =>
                {
                    b.Navigation("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
